version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: quiz-laravel-app-4
    volumes:
      - ./src:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - mysql
    ports:
      - "9000:9000" # PHP-FPM (for nginx)
      - "5173:5173" # Vite dev server
    networks:
      - quiznet

  nginx:
    image: nginx:alpine
    container_name: quiz-nginx-4
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - quiznet

  mysql:
    image: mysql:8.0
    container_name: quiz-mysql-4
    restart: always
    environment:
      MYSQL_DATABASE: quiz
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: quizuser
      MYSQL_PASSWORD: quizpass
    volumes:
      -  ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - quiznet
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: quiz-phpmyadmin-4
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - quiznet

volumes:
  mysql_data:

networks:
  quiznet:
    driver: bridge